mongodb:
  host: "localhost"
  port: "27017"
  database: "user_service"
  auth_db:
  username:
  password:
  collection: "users"

minio:
  endpoint: "localhost:9000"
  storage: "pic-storage"
  secret_k: "JkkMaCUFNZehB4WjHMfetCtgxZoM3nuWG9NNrIAC"
  access_k: "bfdmSZwI8e54ipPaVpRF"

rabbitmq:
  username: "guest"
  password: "guest"
  host: "localhost"
  port: "5672"
  queuename: "Gompress01queue"

